import '@styles/globals.scss';
import {config} from '@fortawesome/fontawesome-svg-core';
import '@fortawesome/fontawesome-svg-core/styles.css';
import Navbar from '@src/components/Navbar';
import MuiProvider from './MuiProvider';
config.autoAddCss = false;

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
};

export default function RootLayout({children}: {children: React.ReactNode}) {
    return (
        <html lang="en">
            <body>
                <MuiProvider>
                    <Navbar currentPage={''} />
                    <main>{children}</main>
                </MuiProvider>
            </body>
        </html>
    );
}
